<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2kaKRKB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2kaKRKB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2kaKRKB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2kaKRKB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2kaKRKB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2kaKRKB',
    'container.build_id' => 'f4690b91',
    'container.build_time' => 1549293914,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2kaKRKB');
